### ISSUE TITLE
Add humidity

### ISSUE THREAD

**Issue by dbrgn** [rust-embedded-community/rust-measurements#19]
Humidity types would be nice. (I personally only need relative humidity. Absolute humidity is quite complex to calculate from relative humidity. Also, it requires the temperature for an estimate to be calculated.)

**Comment by dbrgn** [comment]
Ah, actually I do need absolute humidity (g/m³)... But since the sensor I'm using requires a fixed-point float, I'm probably better off implementing my own wrapper.

Adding support for humidity might still be worthwhile though.

**Comment by eldruin** [comment]
This was done by @pukeko37 in #27. Closing.
