### ISSUE TITLE
Update Changelog with `from_str` methods

### ISSUE THREAD

**Issue by eldruin** [rust-embedded-community/rust-measurements#34]
@drodil could you add your changes to the ChangeLog in a new PR once we have them all merged?
This issue is just so that we do not forget to do it before the next release.

**Comment by drodil** [comment]
Sure thing. I try to get rest of the units done and add the changelog entry!

**Comment by eldruin** [comment]
@drodil BTW, do you participate in the Hacktoberfest 2020? Should I tag the PRs you have submitted?

**Comment by drodil** [comment]
Yes I am participating but already have my 4PRs done. Maybe you could add the hacktoberfest topic for the repo if you want :)

**Comment by eldruin** [comment]
Ok, great :) I would rather not tag the repo to avoid spam I do not have time to deal with.
